name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
      
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.9'
         
     - name: Cache dependencies
       uses: actions/cache@v4
       with:
         path: ~/.cache/pip
         key: cache-be423c6-${{ hashFiles('requirements.txt') }}
         restore-keys: |
           cache-be423c6-
         
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         
     - name: prime-cache-be423c6
       run: |
         if [ -d ~/.cache/pip ]; then
           echo "Cache hit: Dependencies were restored from cache"
         else
           echo "Cache miss: Dependencies were installed fresh"
         fi
         
     - name: 23f3001307@ds.study.iitm.ac.in
       run: echo "Hello, world!"
         
     - name: Test API functionality
       run: |
         python -c "
         import sys
         sys.path.append('api')
         from latency import app, load_latency_data
         print('API imports successfully')
         data = load_latency_data()
         print(f'Loaded {len(data)} latency records')
         print('API functionality test passed')
         "
         
     - name: Deploy to Vercel
       if: github.ref == 'refs/heads/main'
       uses: amondnet/vercel-action@v25
       with:
         vercel-token: ${{ secrets.VERCEL_TOKEN }}
         vercel-org-id: ${{ secrets.ORG_ID }}
         vercel-project-id: ${{ secrets.PROJECT_ID }}
         working-directory: ./